apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwjs-deploy
  labels:
    app: hwjs-app
  annotations:
spec:
  selector:
    matchLabels:
      app: hwjs-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hwjs-app
    spec:
      containers:
      - name: hwjs-app
        image: bmcgair/hwjs:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "12Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
