apiVersion: v1
kind: Service
metadata:
  name: hwjs-service
  labels:
    app: hwjs-app
spec:
  type: LoadBalancer
  selector:
    app: hwjs-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 5000
